### ISSUE TITLE
Accessibility_SP College

### ISSUE THREAD

**Issue by Shamai5** [Examity/Accessibility#1]

**Comment by Shamai5** [comment]
Hi Adarsh,
ADA has to be implemented in SP college Test and Production system.
Thanks,
Shamai

**Comment by examityadarsh** [comment]
Hi Shamai, 
ADA is implemented for SP College

**Comment by Shamai5** [comment]
Hi Sireesha/Arman,
We have completed deploying Accessibility feature in SP college Production system. System is working as expected.

Below are the Quick points on Accessibility feature:

1.	Url : https://prod.examity.com/spcollege (Production system)
2.	Prod credentials for internal Accessibility testing – student02@examity.com/password$ | student03@examity.com/password$ 
3.	Please install Jaws software in your local machine to test accessibility feature. https://www.freedomscientific.com/Downloads/JAWS  
4.	We have developed Accessibility feature only for Level 3 exams.
5.	Please use Internet explorer for testing accessibility, other browsers are not supported.
6.	For Authentication and proctoring exam– we need to use only Zoom not GoToMeeting.
7.	GoToMeeting has no Accessibility functionality.
8.	Zoom inbuilt have Accessibility functionality. – We need to suggest proctors to use Zoom for Accessibility students.

Thanks,
Shamai

**Comment by Shamai5** [comment]
Pending Item: We need to show the color code to WFM and Proctor Inbox Queue to differentiate the Accessibility User.

**Comment by Shamai5** [comment]
Hi @siritips2000 ,

As it is portal task and effect of many pages is this related to Steady state task. Please confirm.
Thanks,
Shamai

**Comment by Shamai5** [comment]
Hi Sireesha,
We are closing this ticket and sending email with to the steady state team to work on the color code in portal.
Thanks,
Shamai
